In [1]:
import tensorflow as tf

In [15]:
tf.__version__

'1.11.0'

#Introduction about tensorflow

## Constant
#Các đại lượng không thay đổi trong quá trình chạy chương trình

In [11]:
x1 = tf.constant(1, name='constant_x1')
print(x1)

x2 = tf.constant(2.0)
print(x2)

x3 = tf.constant(3, dtype='float32')
print(x3)

Tensor("constant_x1_1:0", shape=(), dtype=int32)
Tensor("Const_5:0", shape=(), dtype=float32)
Tensor("Const_6:0", shape=(), dtype=float32)


In [17]:
v1 = tf.constant([1, 2, 3], dtype=tf.float32, name='v1_const_vector')
print(v1)

Tensor("v1_const_vector_1:0", shape=(3,), dtype=float32)


In [19]:
session = tf.Session()

In [20]:
session.run(x1)

1

In [21]:
session.run(x2)

2.0

In [22]:
session.run(x3)

3.0

In [23]:
session.run(v1)

array([1., 2., 3.], dtype=float32)

**Note** tensor có thể là một số thực , số nguyên, chuỗi, ma trận 1D, 2D, 3D, ... multi-demension matrix

In [24]:
# Create tensorflow 2D
v2 = tf.constant([
    [1, 2, 3],
    [3, 4, 5]
], dtype=tf.float32, name='2D_matrix')
print(v2)

Tensor("2D_matrix:0", shape=(2, 3), dtype=float32)


In [25]:
session.run(v2)

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

In [26]:
# Ngoài sử dụng session.run cos thế sử dụng eval với đầu vào là session
v2.eval(session=session)

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

## Perform operators (Các phép toán ma trận)

In [31]:
# Add x1 + x2 (Phép cộng)
y1 = x2 + x3
print(y1)
session.run(y1)

Tensor("add_3:0", shape=(), dtype=float32)


5.0

**Note** Khi xử lý trên tensor thì phải cùng dtype (cùng kiểu dữ liệu)

In [ ]:
v3 = tf.constant([
    [1, 2, 3],
    [3, 4, 5]
], dtype=tf.float32, name='2D_matrix')