In [1]:
import tensorflow as tf

In [15]:
tf.__version__

'1.11.0'

#Introduction about tensorflow

## Constant
#Các đại lượng không thay đổi trong quá trình chạy chương trình

In [11]:
x1 = tf.constant(1, name='constant_x1')
print(x1)

x2 = tf.constant(2.0)
print(x2)

x3 = tf.constant(3, dtype='float32')
print(x3)

Tensor("constant_x1_1:0", shape=(), dtype=int32)
Tensor("Const_5:0", shape=(), dtype=float32)
Tensor("Const_6:0", shape=(), dtype=float32)


In [17]:
v1 = tf.constant([1, 2, 3], dtype=tf.float32, name='v1_const_vector')
print(v1)

Tensor("v1_const_vector_1:0", shape=(3,), dtype=float32)


In [19]:
session = tf.Session()

In [20]:
session.run(x1)

1

In [21]:
session.run(x2)

2.0

In [22]:
session.run(x3)

3.0

In [23]:
session.run(v1)

array([1., 2., 3.], dtype=float32)

**Note** tensor có thể là một số thực , số nguyên, chuỗi, ma trận 1D, 2D, 3D, ... multi-demension matrix

In [24]:
# Create tensorflow 2D
v2 = tf.constant([
    [1, 2, 3],
    [3, 4, 5]
], dtype=tf.float32, name='2D_matrix')
print(v2)

Tensor("2D_matrix:0", shape=(2, 3), dtype=float32)


In [25]:
session.run(v2)

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

In [26]:
# Ngoài sử dụng session.run cos thế sử dụng eval với đầu vào là session
v2.eval(session=session)

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

## Perform operators (Các phép toán ma trận)

In [31]:
# Add x1 + x2 (Phép cộng)
y1 = x2 + x3
print(y1)
session.run(y1)

Tensor("add_3:0", shape=(), dtype=float32)


5.0

**Note** Khi xử lý trên tensor thì phải cùng dtype (cùng kiểu dữ liệu)

In [32]:
v3 = tf.constant([
    [1, 1, 1],
    [3, 3, 2]
], dtype=tf.float32, name='2D_matrix')

In [33]:
y2 = v2 + v3

In [34]:
session.run(y2)

array([[2., 3., 4.],
       [6., 7., 7.]], dtype=float32)

## Placeholder

### Create 
Placeholder sử dụng trong trường hợp chúng ta cần load dữ liệu đầu vào

In [37]:
p1 = tf.placeholder(dtype=tf.float32)
p2 = tf.placeholder(dtype=tf.float32)

In [39]:
# Asign operator for placeholder
o_add = p1 + p2
o_mul = p1 * p2
o_delta = p1**2 + p2 # Phép tính bình phương p1^2 + p2

In [40]:
print(o_add)

Tensor("add_5:0", dtype=float32)


## Feed value for placeholder (Đưa dữ liệu đầu vào cho 1 biến)

In [41]:
d_value = {
    p1 : 20,
    p2 : 10
}

session.run(o_add, feed_dict=d_value) 
# Feed dict: Chúng ta feed 1 mảng giá trị vào trong placeholder

30.0

In [42]:
d_value = {
    p1 : 20,
    p2 : 10
}

session.run(o_delta, feed_dict=d_value) 

410.0

In [43]:
d_value = {
    p1 : 20,
    p2 : 10
}

session.run(o_mul, feed_dict=d_value) 

200.0

In [44]:
session.run([o_add, o_delta], feed_dict=d_value)

[30.0, 410.0]

## Phân biệt Variables và Placeholder

**Variables** Traning mô hình: Các tham số nào cần tranable như các tham số 
cần tối ưu các hệ số wait trong mạng neuron hay các hệ số byat

**Placeholder**  Dùng để load các dữ liệu đầu vào

**Constant** Dùng cho các tham số nào không thay đổi trong chương trình

### Create Variables

In [45]:
var_1 = tf.Variable(name='var_1', initial_value=10)
var_2 = tf.Variable(name='var_2', initial_value=50)
# ten_bien = tf.Variable(name='ten_bien', initial_value gía trị khởi tạo)

**Note** Cần phải khởi tạo biến trước khi đưa vào session và tính toán trên session

In [48]:
session.run(var_1.initializer)
# Hàm khởi tạo variable trước khi đưa vào session

In [49]:
session.run(var_1)

10

**Note** Thay vì khởi tạo từng biến trong 1 chương trình có rất nhiều biến
không thể khởi tạo thủ công như thế.
<br>
Vậy nên sẽ sử dụng hàm: tf.global_variables_initializer().run(session=session)

In [50]:
tf.global_variables_initializer().run(session=session)

In [51]:
session.run(var_2)

50